server:
  port: 19001
  servlet:
    context-path: /
  tomcat:
    uri-encoding: utf-8
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
logging:
  config: classpath:log4j2-spring.xml
